language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - hhvm-nightly

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
  fast_finish: true

install:
    - travis_retry composer self-update
    - composer global require "fxp/composer-asset-plugin:1.0.0-beta3"
    - travis_retry composer update

script: phpunit --bootstrap test/bootstrap.php --configuration phpunit_standard.xml

addons:
  code_climate:
    repo_token: e08ed8d4ba46c32394c98d4b321fb118621e8cf947ae17037606dd6a1d643b6e