language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - hhvm-nightly

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - if [[ "$TRAVIS_PHP_VERSION" = "5.4" ]]; then PHPUNIT_FLAGS="--coverage-clover=coverage.clover"; fi;
matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
    - php: hhvm-nightly
  fast_finish: true

install:
    - travis_retry composer self-update
    - composer global require "fxp/composer-asset-plugin:1.0.0-beta3"
    - travis_retry composer update

script: phpunit --configuration phpunit.xml test $PHPUNIT_FLAGS

after_script:
        - |
            if [ $TRAVIS_PHP_VERSION = '5.4' ]; then
                wget https://scrutinizer-ci.com/ocular.phar
                php ocular.phar code-coverage:upload --format=php-clover coverage.clover
            fi

addons:
  code_climate:
    repo_token: e08ed8d4ba46c32394c98d4b321fb118621e8cf947ae17037606dd6a1d643b6e